
#include "include/libopenmpi_sys.h"

const MPI_Datatype SWIFT_MPI_FLOAT = MPI_FLOAT;
const MPI_Datatype SWIFT_MPI_DOUBLE = MPI_DOUBLE;

const MPI_Comm SWIFT_MPI_COMM_WORLD = MPI_COMM_WORLD;

const MPI_Op SWIFT_MPI_SUM = MPI_SUM;
const MPI_Op SWIFT_MPI_MIN = MPI_MIN;
const MPI_Op SWIFT_MPI_MAX = MPI_MAX;
const MPI_Op SWIFT_MPI_MINLOC = MPI_MINLOC;
const MPI_Op SWIFT_MPI_MAXLOC = MPI_MAXLOC;